config/routes.rb
Rails.application.routes.draw do

  root 'guides#index'
  resources :guides do
    resources :contents
  end
  resources :tags

end

app/models/content.rb
class Content < ActiveRecord::Base
  has_and_belongs_to_many :guides
end

app/models/contents_guides.rb
class ContentsGuides < ActiveRecord::Base
  belongs_to :content
  belongs_to :guide
end

app/models/guide.rb
class Guide < ActiveRecord::Base
  has_and_belongs_to_many :tags
  has_and_belongs_to_many :contents
end

app/models/guides_tags.rb
class GuidesTags < ActiveRecord::Base
  belongs_to :guide
  belongs_to :tag
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :guides
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController

def create
    @guide = Guide.find_by_id(params[:guide_id])
    @content = @guie.contents.create(content_params)
    # current_user.contents << @content

    if @content.save
      flash[:success] = "Content added!"
    end
    redirect_to @guide
  end

private
  def content_params
    params.require(:content).permit(:value)
  end

end

app/controllers/guides_controller.rb
class GuidesController < ApplicationController

  def index
    @guides = Guide.all
    @tags = Tag.all
  end

  def new
    @guide = Guide.new
    @tags = Tag.all
  end

  def create
    @guide = Guide.create(guide_params)
    tags = params[:guide][:tag_ids]

    tags.each do |tag_id|
      @guide.tags << Tag.find(tag_id) unless tag_id.blank?
    end
# render :json => params
redirect_to @guide
end

def show
  @guide = Guide.find(params[:id])
  @tags = Tag.all

  @guide_tags = ""

  @guide.tags.each do |x|
    @guide_tags = @guide_tags + " " + x.name
  end

  # p @guide.title
  # p @guide_tags

  # p "#{@guide_tags} learn"

  request = Typhoeus::Request.new(
    "www.reddit.com/search.json",
    method: :get,
    params: {q: "learn #{@guide_tags}"}
    )

  response = request.run
  data = JSON.parse(response.body)

  @titles = data["data"]["children"].map {|e| e["data"]["title"].to_s}
  @urls = data["data"]["children"].map {|e| e["data"]["url"].to_s}
  # @photos = data["data"]["children"].map {|e| e["data"]["thumbnail"]}

  # p @photos
  # @urls = data["data"]["children"].map {|e| {name: e["data"]["url"].to_s, thing: "blah"}}

  @title_urls = {}
  Hash[@titles.zip(@urls).each {|a,b| @title_urls[a] = b }]

  # p @title_urls
  # p @titles
  # p @urls

end

def edit
  @guide = Guide.find(params[:id])
  @tags = Tag.all
end

def update
  @guide = Guide.update(params[:id], guide_params)

  @guide.tags.clear
  tags = params[:guide][:tag_ids]
  tags.each do |tag_id|
    @guide.tags << Tag.find(tag_id) unless tag_id.blank?
  end
  redirect_to @guide
end

def destroy
  @guide = Guide.find(params[:id])
  Guide.destroy(params[:id])
  redirect_to guides_path
end

private

def guide_params
  params.require(:guide).permit(:title,:description)
end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def index
    @tags = Tag.all
    @guides = Guide.all
  end

  def new
    @tag = Tag.new
  end

  def create
    @tag = Tag.create(tag_params)
    redirect_to tags_path
  end

  def edit
    @tag = Tag.find(params[:id])
  end

  def show
    @tag = Tag.find(params[:id])
  end

  def update
    # @tag = Tag.find(params[:id])
    @tag = Tag.update(params[:id], tag_params)
    redirect_to @tag
  end

  # ADD DESTROY METHOD FOR DELETING A TAG

  def destroy
    @tag = Tag.find(params[:id])
      unless @tag.guides
        Tag.destroy(params[:id])
      else
        flash[:info] = "You removed the #{@tag.name} tag from #{@tag.guides.length} " + "guide".pluralize(@tag.guides.length) + "."
        @tag.guides do |guide|
          guide.tags.delete(params[:id])
      end
      Tag.destroy(params[:id])
    end

    redirect_to tags_path
  end

private

  def tag_params
    params.require(:tag).permit(:name)
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/guides_helper.rb
module GuidesHelper
end

app/views/guides/_form.html.erb
    <%= bootstrap_form_for @guide do |f| %>
    <%= f.text_field :title, label: "Guide Title", :placeholder => "What's the title of this guide?" %>
    <%= f.text_area :description, label: "About Guide", :placeholder => "What is this guide about?" %>
    <%= f.collection_check_boxes :tag_ids, @tags, :id, :name, label: "Guide Tags" %>
    <%= f.submit %>
    <% end %>

app/views/guides/edit.html.erb
<div class="page-header">
  <h1>Update The Guide </h1>
</div>

<div class="row">
  <div class="col-md-6">
    <%= render "form" %>
  </div>
</div>

app/views/guides/index.html.erb
<div class="page-header">
  <h1>Hackables <small>(more like suckables)...Getting started guides</small></h1>
</div>

<div class="row">
<div class="col-md-12">
  <table class="table table-striped">
    <thead><tr><th><b>Guide Title</b></th>
    <th><b>About</b></th><th><b>Tags</b></th>
    <th></th>
      <th></th>
    </tr></thead>
    <% @guides.each do |p| %>
      <tr>
      <td><%= link_to p.title, p %></td>
      <td><%= p.description %></td>
      <td>
        <% p.tags.each do |f| %>
        <span class="label label-default"><%= link_to f.name, f%></span>
        <% end %>
      </td>
        <td>
      <%= link_to "<span class='glyphicon glyphicon glyphicon-pencil' aria-hidden='true'></span>".html_safe, edit_guide_path(p.id), :class=>"btn btn-primary btn-xs" %>
      </td>
      <td>
      <%= link_to "<span class='glyphicon glyphicon glyphicon-trash' aria-hidden='true'></span>".html_safe, guide_path(p.id), :method => :delete, data:{confirm: "Do you want to remove tag from #{p.tags.length} " + "guide".pluralize(p.tags.length) + "."}, :class=>"btn btn-danger btn-xs" %>
      </td>
      </tr>
    <% end %>
  </table>

<%= link_to "<span class='glyphicon glyphicon glyphicon-plus' aria-hidden='true'></span> Add Guide".html_safe, new_guide_path, :class=>"btn btn-default" %>

</div>
</div>

app/views/guides/new.html.erb
<div class="page-header">
  <h1>Create Guide <small>Make a new guide</small></h1>
</div>

<div class="row">
  <div class="col-md-6">
    <%= render "form" %>
  </div>
</div>

app/views/guides/show.html.erb
<div class="page-header">
  <h1><%= @guide.title %> <small><%= @guide.description %></small></h1>
</div>

<div class="row">
<div class="col-md-8">

<ul>
  <% @title_urls.each do |j,k| %>
  <li><a href="<%= k %>" target="_blank"><%= j %></a></li>

  <% end %>
</ul>
</div>
</div>
<div class="row">
<div class="col-md-6">

<b>Tags for this guide:</b>
<ul>
 <% @guide.tags.each do |f| %>
  <li><%= link_to f.name, f %></li>
 <% end %>
</ul>
<%= link_to "<span class='glyphicon glyphicon glyphicon-plus' aria-hidden='true'></span> Edit Guide".html_safe, edit_guide_path, :class=>"btn btn-default" %>
</div>
</div>


<div class="row">
<div class="col-md-6">


 <%= bootstrap_form_for [@guide, @content] do |f| %>
 <%= f.text_area :value, label: "Add content" %>
 <%= f.submit "Content Title", class: "btn btn-primary" %>
 <% end %>


</div>
</div>

app/views/layouts/_flash.html.erb
<% flash.each do |k,v| %>
  <div class="alert alert-<%= k %>">
    <%= v %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hackables</title>
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
<ul class="nav nav-pills">
  <li role="presentation" class=""><a href="<%= root_path %>">All Guides</a></li>
  <li role="presentation"><a href="<%= tags_path %>">Tags</a></li>
  <li role="presentation"><a href="<%= new_guide_path %>">Create Guide</a></li>

</ul>
<%= yield %>

</div>
</body>
</html>

app/views/tags/_form.html.erb
<%= bootstrap_form_for @tag do |f| %>
<%= f.text_field :name, label: "Tag Title", :placeholder => "What's the title of this tag?" %>
<%= f.submit %>
<% end %>

app/views/tags/edit.html.erb
<div class="page-header">
  <h1>Edit Tag <small>Update tag name</small></h1>
</div>

<div class="row">
  <div class="col-md-6">
    <%= render "form" %>
  </div>
</div>

app/views/tags/index.html.erb
<div class="page-header">
  <h1>Hackables <small>Getting started guides</small></h1>
</div>

<div class="row">
<div class="col-md-12">
    <%= render "layouts/flash" %>

<h1>Tags</h1>
  <table class="table table-striped">
    <thead>
      <tr>
        <th><b>Tag Title</b></th>
        <th><b>Associated Guides</b></th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <% @tags.each do |t| %>
      <tr>
      <td>
      <%= link_to t.name, t %>
      </td>
      <td>
      <% t.guides.each do |g| %>
        <span class="label label-default"><%= link_to g.title, g %></span>
      <% end %>
      </td>
      <td>
      <%= link_to "<span class='glyphicon glyphicon glyphicon-pencil' aria-hidden='true'></span>".html_safe, edit_tag_path(t.id), :class=>"btn btn-primary btn-xs" %>
      </td>
      <td>
      <%= link_to "<span class='glyphicon glyphicon glyphicon-trash' aria-hidden='true'></span>".html_safe, tag_path(t.id), :method => :delete, data:{confirm: "Do you want to remove tag from #{t.guides.length} " + "guide".pluralize(t.guides.length) + "."}, :class=>"btn btn-danger btn-xs" %>
      </td>
      </tr>

    <% end %>
  </table>

  <%= link_to "<span class='glyphicon glyphicon glyphicon-plus' aria-hidden='true'></span> Add Tag".html_safe, new_tag_path, :class=>"btn btn-default" %>

</div>
</div>

app/views/tags/new.html.erb
<div class="page-header">
  <h1>Add Tag <small>Add a new guide</small></h1>
</div>

<div class="row">
  <div class="col-md-6">
    <%= render "form" %>
  </div>
</div>

app/views/tags/show.html.erb
<div class="page-header">
  <h1><%= @tag.name %> </small></h1>
</div>

<div class="row">
<div class="col-md-4">
<b>Associated Guides:</b>
<ul>
 <% @tag.guides.each do |f| %>
  <li><%= link_to f.title, f %>
</li>
 <% end %>
</ul>

<%= link_to "<span class='glyphicon glyphicon glyphicon-plus' aria-hidden='true'></span> Edit Tag".html_safe, edit_tag_path, :class=>"btn btn-default" %>

</div>
</div>